
services:
  krakend:
    image: krakend:2.12.0
    ports:
      - "8080:8080"
    volumes:
      - ./config/krakend.json:/etc/krakend/krakend.json
    networks:
      - proxy

networks:
  proxy:
    external: true
    