services:
  # -----------------------------------------------
  # PostgreSQL Database
  # -----------------------------------------------
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - bootstrap_proxy

  # -----------------------------------------------
  # Redis (with Streams support)
  # -----------------------------------------------
  redis:
    image: redis:8.4.0
    container_name: redis
    restart: always
    command: ["redis-server", "--save", "", "--appendonly", "yes"]
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
    networks:
      - bootstrap_proxy

networks:
  bootstrap_proxy:
    external: true