---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Development:
    - Github:
        - icon: github.png
          href: {{HOMEPAGE_VAR_GITHUB_URL}}
    - Cloudflare:
        - icon: cloudflare.png
          href: {{HOMEPAGE_VAR_CLOUDFLARE_URL}}

- Social:
    - Reddit:
        - icon: reddit.png
          href: {{HOMEPAGE_VAR_REDDIT_URL}}
    - Discord:
        - icon: discord.png
          href: {{HOMEPAGE_VAR_DISCORD_URL}}
