---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Bookmarks:
    - Github:
        - icon: github.png
          href: https://github.com/atselvan
    - Reddit:
        - icon: reddit.png
          href: https://reddit.com/
    - Namecheap:
        - icon: namecheap.png
          href: https://ap.www.namecheap.com/Domains/DomainControlPanel/atselvan.com/advancedns
