---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Server Monitoring:
    - CPU Usage:
            widget:
                type: glances
                url: {{HOMEPAGE_VAR_GLANCES_URL}}
                username: {{HOMEPAGE_VAR_GLANCES_USERNAME}}
                password: {{HOMEPAGE_VAR_GLANCES_PASSWORD}}
                version: 4
                metric: cpu

    - Memory Usage:
            widget:
                type: glances
                url: {{HOMEPAGE_VAR_GLANCES_URL}}
                username: {{HOMEPAGE_VAR_GLANCES_USERNAME}}
                password: {{HOMEPAGE_VAR_GLANCES_PASSWORD}}
                version: 4
                metric: memory

    - Network Usage:
            widget:
                type: glances
                url: {{HOMEPAGE_VAR_GLANCES_URL}}
                username: {{HOMEPAGE_VAR_GLANCES_USERNAME}}
                password: {{HOMEPAGE_VAR_GLANCES_PASSWORD}}
                version: 4
                metric: network:en0

    - Disk Usage:
            widget:
                type: glances
                url: {{HOMEPAGE_VAR_GLANCES_URL}}
                username: {{HOMEPAGE_VAR_GLANCES_USERNAME}}
                password: {{HOMEPAGE_VAR_GLANCES_PASSWORD}}
                version: 4
                metric: disk:disk0

- Server Management Applications:
    - Proxy:
        icon: nginx-proxy-manager.png
        description: Reverse Proxy
        href: {{HOMEPAGE_VAR_NPM_URL}}
        siteMonitor: {{HOMEPAGE_VAR_NPM_URL}}
        container: proxy
        widget:
            type: npm
            url: {{HOMEPAGE_VAR_NPM_URL}}
            username: {{HOMEPAGE_VAR_NPM_USERNAME}}
            password: {{HOMEPAGE_VAR_NPM_PASSWORD}}

    - Portainer:
        icon: portainer.png
        description: Container management
        href: {{HOMEPAGE_VAR_PORTAINER_URL}}
        siteMonitor: {{HOMEPAGE_VAR_PORTAINER_URL}}
        container: portainer
        widget:
            type: portainer
            url: {{HOMEPAGE_VAR_PORTAINER_URL}}
            env: 1
            kubernetes: false
            key: {{HOMEPAGE_VAR_PORTAINER_API_KEY}}

    - Synology:
        icon: synology.png
        description: Synology NAS
        href: {{HOMEPAGE_VAR_NAS_URL}}
        siteMonitor: {{HOMEPAGE_VAR_NAS_URL}}
        widget:
          type: diskstation
          url: {{HOMEPAGE_VAR_NAS_URL}}
          username: {{HOMEPAGE_VAR_NAS_USERNAME}}
          password: {{HOMEPAGE_VAR_NAS_PASSWORD}}
          fields: 
            - uptime
            - resources.cpu
            - resources.mem

    - Glances: 
        icon: glances.png
        href: {{HOMEPAGE_VAR_GLANCES_URL}}
        siteMonitor: {{HOMEPAGE_VAR_GLANCES_URL}}
        widget:
            type: glances
            url: {{HOMEPAGE_VAR_GLANCES_URL}}
            username: {{HOMEPAGE_VAR_GLANCES_USERNAME}}
            password: {{HOMEPAGE_VAR_GLANCES_PASSWORD}}
            version: 4
            metric: info

    - Uptime:
        icon: uptime-kuma.png
        href: {{HOMEPAGE_VAR_UPTIME_KUMA_URL}}
        siteMonitor: {{HOMEPAGE_VAR_UPTIME_KUMA_URL}}
        container: uptime-kuma
        widget:
            type: uptimekuma
            url: {{HOMEPAGE_VAR_UPTIME_KUMA_URL}}
            slug: mac-server

    - Syncthing MacServer:
        icon: syncthing.png
        description: Keep data in sync
        href: {{HOMEPAGE_VAR_SYNCTHING_MACSERVER_URL}}
        siteMonitor: {{HOMEPAGE_VAR_SYNCTHING_MACSERVER_URL}}

    - Syncthing DS216:
        icon: syncthing.png
        description: Keep data in sync
        href: {{HOMEPAGE_VAR_SYNCTHING_DS216_URL}}
        siteMonitor: {{HOMEPAGE_VAR_SYNCTHING_DS216_URL}}

- Applications:
    - Jellyfin:
        icon: jellyfin.png
        description: Jellyfin media server
        href: {{HOMEPAGE_VAR_JELLYFIN_URL}}
        siteMonitor: {{HOMEPAGE_VAR_JELLYFIN_URL}}
        widget:
            type: jellyfin
            url: {{HOMEPAGE_VAR_JELLYFIN_URL}}
            key: {{HOMEPAGE_VAR_JELLYFIN_API_KEY}}
            enableBlocks: true 
            enableNowPlaying: false 
            enableUser: true 
            enableMediaControl: false 
            showEpisodeNumber: true 
            expandOneStreamToTwoRows: false
    
    - Immich:
        icon: immich.png
        description: Immich photo and video gallery
        href: {{HOMEPAGE_VAR_IMMICH_URL}}
        siteMonitor: {{HOMEPAGE_VAR_IMMICH_URL}}
        widget:
            type: immich
            url: {{HOMEPAGE_VAR_IMMICH_URL}}
            key: {{HOMEPAGE_VAR_IMMICH_API_KEY}}
            version: 2

    - Actual Budget:
        icon: actual-budget.png
        description: Actual budget
        href: {{HOMEPAGE_VAR_ACTUALBUDGET_URL}}
        siteMonitor: {{HOMEPAGE_VAR_ACTUALBUDGET_URL}}

- Media Management Applications:
    - Jellyseerr:
        icon: jellyseerr.png
        description: Jellyseerr media downloader
        href: {{HOMEPAGE_VAR_JELLYSEERR_URL}}
        siteMonitor: {{HOMEPAGE_VAR_JELLYSEERR_URL}}
        widget:
            type: jellyseerr
            url: {{HOMEPAGE_VAR_JELLYSEERR_URL}}
            key: {{HOMEPAGE_VAR_JELLYSEERR_API_KEY}}

    - Prowlarr:
        icon: prowlarr.png
        description: Prowlarr media downloader
        href: {{HOMEPAGE_VAR_PROWLARR_URL}}
        siteMonitor: {{HOMEPAGE_VAR_PROWLARR_URL}}
        widget:
            type: prowlarr
            url: {{HOMEPAGE_VAR_PROWLARR_URL}}
            key: {{HOMEPAGE_VAR_PROWLARR_API_KEY}}

    - Bazarr:
        icon: bazarr.png
        description: Bazarr media downloader
        href: {{HOMEPAGE_VAR_BAZARR_URL}}
        siteMonitor: {{HOMEPAGE_VAR_BAZARR_URL}}
        widget:
            type: bazarr
            url: {{HOMEPAGE_VAR_BAZARR_URL}}
            key: {{HOMEPAGE_VAR_BAZARR_API_KEY}}

    - Radarr:
        icon: radarr.png
        description: Radarr media downloader
        href: {{HOMEPAGE_VAR_RADARR_URL}}
        siteMonitor: {{HOMEPAGE_VAR_RADARR_URL}}
        widget:
            type: radarr
            url: {{HOMEPAGE_VAR_RADARR_URL}}
            key: {{HOMEPAGE_VAR_RADARR_API_KEY}}

    - Sonarr:
        icon: sonarr.png
        description: Sonarr media downloader
        href: {{HOMEPAGE_VAR_SONARR_URL}}
        siteMonitor: {{HOMEPAGE_VAR_SONARR_URL}}
        widget:
            type: sonarr
            url: {{HOMEPAGE_VAR_SONARR_URL}}
            key: {{HOMEPAGE_VAR_SONARR_API_KEY}}

    - QbitTorrent:
        icon: qbittorrent.png
        description: QbitTorrent media downloader
        href: {{HOMEPAGE_VAR_QBITTORRENT_URL}}
        siteMonitor: {{HOMEPAGE_VAR_QBITTORRENT_URL}}
